/*
Name: prepare_package_xml.js
Desc: Simple script that is used to take a JSON collection of Salesforce Objects names and inject it into a package.xml file using merge field
replacement mechanism. The merge field should be located inside a <type> node inside a package_template.xml file.
Author: Shion Earl-Krogseth
Date: 08/07/19
Required: 
    npm install replace;
Required Files (local to script): 
    package_template.xml - the package.xml template to be used. This must include the merge field <!#ADD_CUSTOM_OBJECT_LIST_HERE>
    sfdc_object_collection.json - The generated json file that can be imported to use as a collection. 
    This should be generated by SFDX commands in a previous job to this script being fired.\

1) run the following sfdx: sfdx force:schema:sobject:list -c all >  sfdc_object_collection.json
2) Ensure that all files are local. Run this nodejs script to create the new package xml.
    
*/

var replace = require("replace");
var fs = require('fs');

fs.copyFile('package_template.xml', 'package.xml', (err) => {
    if (err) throw err;
    console.log('Copy of package_template.xml was created for generation process');
  });

var json = JSON.parse(fs.readFileSync('sfdc_object_collection.json'));
var packagexml = fs.readFileSync('package.xml')
var xmlString;
for(var i = 0; i < json.length; i++) {
    var obj = json[i];
    if(xmlString == null)
    {
        xmlString = '<members>' + obj + '</members>' + '\n\t';
    } else {        
        xmlString = xmlString + '<members>' + obj + '</members>';
        if(i != json.length - 1) xmlString = xmlString + '\n\t';
    }
}
console.log(xmlString);

replace({
    regex: "<!#ADD_CUSTOM_OBJECT_LIST_HERE>",
    replacement: xmlString,
    paths: ['package.xml'],
    recursive: true,
    silent: true,
});
